### ISSUE TITLE
provide function to load data

### ISSUE THREAD

**Issue by jutanke** [bonn-activity-maps/aikapi#1]
provided mp4 and data json - load data such as:

* persons for a given frame
* each person might have one or more activity labels
* provide camera images for the frame
* provide calibration for the frame

Please multiply the frame by *2*

**Comment by almartmen** [comment]
The time is what needs to be upsampled.
Actions that go from 10 to 15 become actions that go from 20 to 30, so for the new frames we just take the previous action.
Annotations like PersonAIK objects should be interpolated for the new upscaled frames:

- Since we downscaled the videos our annotations correspond to the even frames of the original videos. So for the odd frames we need to take the surrounding even frames and interpolate between them.

```
Annotation -> real frame
1 -> 1
2 -> 3
3 -> 5

To get for example the real frame 1 we would need to take annotations 0 and 1 and interpolate.
